services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: database
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready --dbname=$${POSTGRES_DB} --username=$${POSTGRES_USER}']
      interval: 1s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      dockerfile_inline: |
        # syntax=docker/dockerfile:1
        FROM node:lts
        WORKDIR /app
        COPY . ./
        RUN npm ci
        CMD ["npm", "run", "dev"]
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://username:password@postgres/database
      AUTH_SECRET: s3cret*
      GOOGLE_CLIENT_ID: updateMe!
      GOOGLE_CLIENT_SECRET: alsoMe#
    volumes:
      - ./:/app
    ports:
      - 3000:3000

volumes:
  pgdata:
